// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function ACTest(arg1:gui.ACTestRequest):Promise<gui.ACTestResponse>;

export function FilterTest(arg1:gui.FilterTestRequest):Promise<gui.FilterTestResponse>;

export function LexiconTest(arg1:gui.LexiconTestRequest):Promise<gui.LexiconTestResponse>;

export function NormalizeTest(arg1:gui.NormalizeTestRequest):Promise<gui.NormalizeTestResponse>;

export function TrieTest(arg1:gui.TrieTestRequest):Promise<gui.TrieTestResponse>;

export function WordsPath():Promise<string>;
