// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ACTest(arg1) {
  return window['go']['main']['App']['ACTest'](arg1);
}

export function FilterTest(arg1) {
  return window['go']['main']['App']['FilterTest'](arg1);
}

export function LexiconTest(arg1) {
  return window['go']['main']['App']['LexiconTest'](arg1);
}

export function NormalizeTest(arg1) {
  return window['go']['main']['App']['NormalizeTest'](arg1);
}

export function TrieTest(arg1) {
  return window['go']['main']['App']['TrieTest'](arg1);
}

export function WordsPath() {
  return window['go']['main']['App']['WordsPath']();
}
